name: Build and Push Caddy

on:
  push:
    branches: [main]
    paths:
      - 'caddy-docker-cloudflare/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  run-build:
    uses: ./.github/workflows/reusable-build.yaml
    with:
      image_name: caddy-docker-cloudflare
      context_path: ./caddy-docker-cloudflare
